---
title: "Monitoramento Reefcheck REBIO e Entorno"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(reshape2)
library(leaflet)
library(ggplot2)
library(vegan)
library(plotly)
library(lubridate)
library(dplyr)

library(RColorBrewer)
palette(brewer.pal(8, "Set2"))
```
```{r dataread, include=FALSE}

iscDF<- read.csv("monitoring_rebio_ISC_2020_05_07.csv", header=T, sep=";", dec=".", na.strings = "NA", stringsAsFactors = T) #check if it's possible to download data from google drive  
subsDF<- read.csv("monitoring_rebio_SUBS_2020_05_07.csv", header=T, sep=";", dec=".")
iscDF
subsDF

```

General Information
======================================================================

Row
----------------------------------------------------------------------


### REBIO Arvoredo e Entorno 2020

```{r map}
## get lat lon
siteCoords = iscDF %>% dplyr::group_by(site_code)%>% 
  dplyr::summarise(lng = mean(lon_dd, na.rm=T), 
            lat = mean(lat_dd, na.rm=T))

## get total abund by site
siteAbund = iscDF %>%  
  filter(taxon != "Lixo_comum" & taxon != "Lixo_de_pesca" & abund!= "0")%>% #excluding fishing trash and abund zero
  dplyr::group_by(site_code) %>% 
  dplyr::summarise(sumAbund = sum(abund, na.rm=T),
  richness = n_distinct(taxon)) 


## add abund and cover to coords
siteCoords = full_join(siteCoords, siteAbund)

## create a color palette
pal <- colorFactor(palette = c('#a6cee3','#1f78b4','#b2df8a','#33a02c',
                               '#fb9a99','#e31a1c','#fdbf6f','#ff7f00',
                               '#cab2d6','#6a3d9a','#ffff99','#b15928'),
                              domain= c("AR", "DE","DS","ESTL","ESTO",
                                        "FA", "NL","RN","SA", "SC", 
                                        "TS","XV"))

## make leaflet map
leaflet(siteCoords) %>% 
  addTiles() %>% 
  addCircleMarkers(label = ~paste0(site_code,' / N. Taxa: ', richness), 
                   radius = ~100 * sumAbund/(sumAbund)/4,
                   color = ~pal(site_code), 
                   fillOpacity = 0.9,
                   stroke = T,
                   clusterOptions = markerClusterOptions()) %>% 
  addMiniMap(toggleDisplay = T)

```

### Taxonomic rank distribution

```{r taxonrank}
library(worms)
scNames = unique(iscDF$AphiaID)
scNames = scNames[!is.na(scNames)] #excluded fishing thrash/thrash

## get taxon rank from WoRMS
scNames.rank = wormsbyid(x = scNames, verbose = F)

## summarizes the results
taxranks = as.data.frame(table(scNames.rank$rank))

## make a donut
p = taxranks %>% plot_ly(labels = ~Var1, values=~Freq) %>% 
  add_pie(hole=0.6) %>% 
  layout(title = ~paste0("Total number of Taxa: ", length(scNames))) 

plotly::config(p,displayModeBar = F) 



```

Taxon List
======================================================================


Row 
-----------------------------------------------------------------------


### Taxa list: number of quadrats each taxa where found 

```{r taxalist}
spRanks = scNames.rank[,c("AphiaID", "rank")] 

## add taxon rank to occurrence table
iscDF = full_join(iscDF, spRanks)
  

taxaTable = iscDF %>% 
  dplyr::group_by(AphiaID) %>% dplyr::filter(!is.na(AphiaID) & taxon!="NA" & abund!="0" ) %>%  # zeros taxa out of data frame
  dplyr::summarise(taxon = unique(taxon), 
            rank = unique(rank), 
            rocky_shore = sum(habitat=="rocky_shore", na.rm=T), 
            rodolith_bed = sum(habitat=="rodolith_bed", na.rm=T), 
            m_decactis_bed = sum(habitat=="m_decactis_bed", na.rm=T))

knitr::kable(taxaTable)



```
Taxon number by Substrate Type 
======================================================================

Row
-----------------------------------------------------------------------

### Number of taxa per site and stratum

```{r taxasite}
taxaquadrat = iscDF %>% filter(taxon!="Lixo_de_pesca", taxon!="Lixo_comun", abund==0) %>% # cut the 0 abund on data
  group_by(site_code,habitat, sampleID)%>% 
  dplyr::summarise(taxon_n = n())


  taxaquadrat$habitat = factor(taxaquadrat$habitat, levels = c("rocky_shore", "rodolith_bed", "m_decactis_bed"))

pp = ggplot(taxaquadrat, aes( habitat, taxon_n, fill= habitat))#order plot by latitude
pp + geom_boxplot() + ylab("Taxa per transect(n)") + 
  facet_grid(~site_code) + 
  theme_bw(base_size = 9) + theme(legend.position = "bottom") + 
  scale_x_discrete(labels=c("RS", "RB", "MD"))


```

Species Frequency by Substrate Type 
======================================================================

### Species frequency

```{r}
taxafreq = iscDF %>% dplyr::filter(!is.na(AphiaID & abund!="0")) %>% 
  dplyr::group_by(site_code, habitat, taxon) %>% 
  dplyr::summarise(sppfreq = n()) %>% 
  dplyr::arrange(sppfreq) %>% 
  dplyr::mutate(sppacum = cumsum(sppfreq))

pp = ggplot(taxafreq, aes(taxon, sppfreq, fill=habitat))
pp = pp + geom_bar(stat="identity") + coord_flip() + facet_grid(~site_code) + 
  theme_bw(base_size = 9) + xlab("") + ylab("number of transects present")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```






Rarefaction Curves
=======================================================


Row
-------------------------------------------------------

### Rocky Shore


```{r rarerock}
## filter by habitat
Occurrence.site = iscDF %>% filter(habitat=="rocky_shore", !is.na(AphiaID) & abund!="0")

## do it by site
siteNames = unique(Occurrence.site$site_code)

## empty DF for results
sppAccum = data.frame(site = character(),
                      habitat = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(sampleID~AphiaID, data=subset(Occurrence.site, site_code==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "rarefaction")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

##Add custon pallete, same color showed in map


## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp = pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of individuals") + ylab("Accumulated number of Species")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```

### Rodolith bed


```{r rarerodo} 
## filter by habitat
Occurrence.site = iscDF %>% filter(habitat=="rodolith_bed", !is.na(AphiaID) & abund!="0")

## do it by site
siteNames = unique(Occurrence.site$site_code)

## empty DF for results
sppAccum = data.frame(site = character(),
                      habitat = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(sampleID~AphiaID, data=subset(Occurrence.site, site_code==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "rarefaction")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp = pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of individuas") + ylab("Accumulated number of Species")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```

### Madracis decactis bed

```{r raredecactis}
## filter by habitat
Occurrence.site = iscDF %>% filter(habitat=="m_decactis_bed", !is.na(AphiaID) & abund!="0")

## do it by site
siteNames = unique(Occurrence.site$site_code)

## empty DF for results
sppAccum = data.frame(site = character(),
                      habitat = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(sampleID~AphiaID, data=subset(Occurrence.site, site_code==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "rarefaction")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp = pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of individuals") + ylab("Accumulated number of Species")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```

