---
title: "Dados do Reefcheck REBIO e Entorno"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(reshape2)
library(leaflet)
library(ggplot2)
library(vegan)
library(plotly)
library(lubridate)
library(dplyr)

library(RColorBrewer)
palette(brewer.pal(8, "Set2"))
```
```{r dataread, include=FALSE}

iscDF<- read.csv("monitoring_rebio_isc_2020.csv", header=T, sep=";", dec=".", na.strings = "NA", stringsAsFactors = T)
subsDF<- read.csv("monitoring_rebio_subs_2020.csv", header=T, sep=";", dec=".")
iscDF
subsDF

```

Informações Gerais
======================================================================

Row
-----------------------------------------------------------------------


### REBIO Arvoredo e Entorno 2020

```{r map}
## get lat lon
siteCoords = iscDF %>% dplyr::group_by(site)%>% 
  dplyr::summarise(lng = mean(lon_dd, na.rm=T), 
            lat = mean(lat_dd, na.rm=T))

## get total abund by site
siteAbund = iscDF %>%  
  filter(taxon != "Lixo_comum" & taxon != "Lixo_de_pesca" & abund != "0")%>% #excluding fishing trash and abund zero
  dplyr::group_by(site) %>% 
  dplyr::summarise(sumAbund = sum(abund, na.rm=T),
  richness = n_distinct(taxon)) 


## add abund and cover to coords
siteCoords = full_join(siteCoords, siteAbund)

## create a color palette
pal <- colorFactor(palette = c('#a6cee3','#1f78b4','#b2df8a'),
                   domain= c('DN', 'RN', 'TS' ))

## make leaflet map
leaflet(siteCoords) %>% 
  addTiles() %>% 
  addCircleMarkers(label = ~paste0(site,' / N. Taxa: ', richness), 
                   radius = ~100 * sumAbund/(sumAbund)/4,
                   color = ~pal(site), 
                   fillOpacity = 0.6,
                   stroke = F,
                   clusterOptions = markerClusterOptions()) %>% 
  addMiniMap(toggleDisplay = T)

```

### Taxonomic rank distribution

```{r taxonrank}
library(worms)
scNames = unique(iscDF$AphiaID)
scNames = scNames[!is.na(scNames)] #excluded fishing thrash/thrash

## get taxon rank from WoRMS
scNames.rank = wormsbyid(x = scNames, verbose = F)

## summarizes the results
taxranks = as.data.frame(table(scNames.rank$rank))

## make a donut
p = taxranks %>% plot_ly(labels = ~Var1, values=~Freq) %>% 
  add_pie(hole=0.6) %>% 
  layout(title = ~paste0("Total number of Taxa: ", length(scNames))) 

plotly::config(p,displayModeBar = F) 



```

Row
-----------------------------------------------------------------------

### Number of taxa per site and stratum

```{r taxasite}
taxaquadrat = iscDF %>% filter(taxon!="Lixo_de_pesca", taxon!="Lixo_comun", abund==0) %>% #on new csv this will not be necessary
  group_by(site,habitat, trans_n)%>% 
  dplyr::summarise(taxon_n = n())


  taxaquadrat$habitat = factor(taxaquadrat$habitat, levels = c("rocky_shore", "rodolith_bed", "m_decactis_bed"))

pp = ggplot(taxaquadrat, aes( habitat, taxon_n, fill= habitat))
pp = pp + geom_boxplot() + ylab("Taxa per transect(n)") + 
  facet_grid(~site) + 
  theme_bw(base_size = 9) + theme(legend.position = "none")


ggplotly(pp) %>% plotly::config(displayModeBar = F) 


```





### Taxa list: number of quadrats where found 

```{r taxalist}
spRanks = scNames.rank[,c("AphiaID", "rank")] #check zeros in abund

## add taxon rank to occurrence table
iscDF = full_join(iscDF, spRanks)
  

taxaTable = iscDF %>% 
  dplyr::group_by(AphiaID) %>% dplyr::filter(!is.na(AphiaID)) %>% 
  dplyr::summarise(taxon = unique(taxon), 
            rank = unique(rank), 
            rocky_shore = sum(habitat=="rocky_shore", na.rm=T), 
            rodolith_bed = sum(habitat=="rodolith_bed", na.rm=T), 
            m_decactis_bed = sum(habitat=="m_decactis_bed", na.rm=T))

knitr::kable(taxaTable)



```

Indicators
=======================================================


Row
-------------------------------------------------------

### Rocky Shore


```{r}
## filter by habitat
Occurrence.site = iscDF %>% filter(habitat=="rocky_shore", !is.na(AphiaID) & abund!="0")

## do it by site
siteNames = unique(Occurrence.site$site)

## empty DF for results
sppAccum = data.frame(site = character(),
                      habitat = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(sampleID~AphiaID, data=subset(Occurrence.site, site==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "random")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of samples") + ylab("Accumulated number of Spp")

```

Row
-------------------------------------------------------

### Rodolith bed


```{r}
## filter by habitat
Occurrence.site = iscDF %>% filter(habitat=="rodolith_bed", !is.na(AphiaID) & abund!="0")

## do it by site
siteNames = unique(Occurrence.site$site)

## empty DF for results
sppAccum = data.frame(site = character(),
                      habitat = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(sampleID~AphiaID, data=subset(Occurrence.site, site==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "random")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of samples") + ylab("Accumulated number of Spp")

```


Row
-------------------------------------------------------

### Madracis decactis bed

```{r}
## filter by habitat
Occurrence.site = iscDF %>% filter(habitat=="m_decatis_bed", !is.na(AphiaID) & abund!="0")

## do it by site
siteNames = unique(Occurrence.site$site)

## empty DF for results
sppAccum = data.frame(site = character(),
                      habitat = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(sampleID~AphiaID, data=subset(Occurrence.site, site==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "random")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of samples") + ylab("Accumulated number of Spp")

```

